# Generated by Django 2.2 on 2021-03-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
